name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - gdal
  - pip:
    - affine==2.4.0
    - attrs==23.2.0
    - certifi==2024.2.2
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - fiona==1.9.6
    - GDAL==3.9.0
    - geopandas==0.14.4
    - numpy==1.26.4
    - packaging==24.0
    - pandas==2.2.2
    - pyparsing==3.1.2
    - pyproj==3.6.1
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - rasterio==1.3.10
    - shapely==2.0.4
    - six==1.16.0
    - snuggs==1.4.7
    - tzdata==2024.1
