name: OS-only-GIS
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - geopandas==1.0.1
  - gdal
  - pyshp
  - shapely
  - rasterio==1.4.3
  - fiona==1.9.6
  - packaging==24.2
